AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1.2
  Exclude:
    - 'spec/**/*'
    - 'newebpay-turbo.gemspec'
    - 'lib/generators/newebpay/templates/**/*'
    - vendor/bundle/**/*

Style/DoubleNegation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'lib/**/*'
    - 'spec/**/*'
Metrics/BlockLength:
  Exclude:
    - 'lib/**/*'
    - 'spec/**/*'
Layout/LineLength:
  Exclude:
    - 'lib/**/*'
    - 'spec/**/*'
Metrics/ClassLength:
  Exclude:
    - 'lib/**/*'
    - 'spec/**/*'
Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/**/*'
    - 'spec/**/*'
Metrics/MethodLength:
  Exclude:
    - 'lib/**/*'
    - 'spec/**/*'
Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/**/*'
    - 'spec/**/*'
Naming/AccessorMethodName:
  Exclude:
    - 'lib/**/*'
    - 'spec/**/*'
Naming/PredicateName:
  Exclude:
    - 'lib/**/*'
    - 'spec/**/*'
Style/Documentation:
  Exclude:
    - 'lib/**/*'
    - 'spec/**/*'