name: rspec

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - '**'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true

      - name: Run RSpec
        env: 
          MerchantID: ${{ secrets.MerchantID }}
          HashIV: ${{ secrets.HashIV }}
          HashKey: ${{ secrets.HashKey }}
          Version: ${{ secrets.Version }}
          TZ: ${{ secrets.TZ }}
        run: bundle exec rspec

      - name: Run Rubocop
        run: bundle exec rubocop